// Generates src/generated/commit.ts with the current git commit SHA so the
// running worker can render it in the page footer. Run before every build/deploy.
//
// Resolution order:
//   1. WORKERS_CI_COMMIT_SHA   (set by Cloudflare Workers Builds)
//   2. CF_PAGES_COMMIT_SHA     (set by Cloudflare Pages, kept as a fallback)
//   3. GITHUB_SHA              (set by GitHub Actions)
//   4. `git rev-parse HEAD`    (local dev)
//   5. "unknown"               (no git context — shouldn't happen in practice)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execSync } from "node:child_process";

function resolveSha() {
  const ciSha =
    process.env.WORKERS_CI_COMMIT_SHA ||
    process.env.CF_PAGES_COMMIT_SHA ||
    process.env.GITHUB_SHA;
  if (ciSha) return ciSha.trim();
  try {
    return execSync("git rev-parse HEAD", { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

const sha = resolveSha();
const short = sha === "unknown" ? sha : sha.slice(0, 7);

// Only write when contents would actually change. wrangler is invoked as
// `build.command` here AND on every dev-server rebuild, so unconditional
// writes touch the file's mtime each loop → wrangler's file watcher sees the
// "change" → restart → re-runs build.command → another touch → infinite
// restart loop. Skipping the write when the SHA is unchanged breaks that.
const next = `// AUTO-GENERATED by scripts/write-commit.mjs. Do not edit; do not commit.
export const GIT_COMMIT_FULL = ${JSON.stringify(sha)};
export const GIT_COMMIT_SHORT = ${JSON.stringify(short)};
`;
const target = "src/generated/commit.ts";
let current = "";
try {
  current = readFileSync(target, "utf8");
} catch {
  // file doesn't exist yet — fall through to write
}
if (current === next) {
  console.log(`scripts/write-commit.mjs: ${target} already up-to-date (${short})`);
} else {
  mkdirSync("src/generated", { recursive: true });
  writeFileSync(target, next);
  console.log(`scripts/write-commit.mjs: wrote ${target} (${short})`);
}
